// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdWNn4SETojTtfJAkdmcXtfBI84cds3g',
    appId: '1:388290760470:web:78da838adcb4c210528a37',
    messagingSenderId: '388290760470',
    projectId: 'stylish-96aad',
    authDomain: 'stylish-96aad.firebaseapp.com',
    storageBucket: 'stylish-96aad.firebasestorage.app',
    measurementId: 'G-G4XZ9NGS5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHQQ06hsppIn5mau8JzLwe5IVDJ3j3zA',
    appId: '1:388290760470:android:411ba1930a5a1fbc528a37',
    messagingSenderId: '388290760470',
    projectId: 'stylish-96aad',
    storageBucket: 'stylish-96aad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUYVl7uUr4bKTiIn4lkFXtPSX1oYOEmM',
    appId: '1:388290760470:ios:d161b9cee6e75ad7528a37',
    messagingSenderId: '388290760470',
    projectId: 'stylish-96aad',
    storageBucket: 'stylish-96aad.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUYVl7uUr4bKTiIn4lkFXtPSX1oYOEmM',
    appId: '1:388290760470:ios:d161b9cee6e75ad7528a37',
    messagingSenderId: '388290760470',
    projectId: 'stylish-96aad',
    storageBucket: 'stylish-96aad.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIdWNn4SETojTtfJAkdmcXtfBI84cds3g',
    appId: '1:388290760470:web:a28d248fbf32197d528a37',
    messagingSenderId: '388290760470',
    projectId: 'stylish-96aad',
    authDomain: 'stylish-96aad.firebaseapp.com',
    storageBucket: 'stylish-96aad.firebasestorage.app',
    measurementId: 'G-BG4WXYG3WS',
  );
}
